version: "3.8"

services:
  trainova-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: trainova-ml
    container_name: trainova-ml-api
    ports:
      - "5010:5010"
    volumes:
      # Mount data directory to persist model and training data
      - trainova_data:/app/trainova_ml/data
    restart: unless-stopped
    environment:
      - PORT=5010
      - FLASK_ENV=production

  trainova-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: trainova-ml
    container_name: trainova-ml-cli
    volumes:
      - trainova_data:/app/trainova_ml/data
    entrypoint: ["python", "trainova-cli.py"]
    profiles: ["cli"]
    # CLI container won't start by default, use profiles to run it:
    # docker-compose --profile cli run trainova-cli predict --exercise "Bench Press"

volumes:
  trainova_data:
    # This creates a named volume to persist data between container restarts
